        <div class="board_status">
                <span class="board_res_no">No:<b><!###BOARD_RES_NO###!></b></span>
                <span class="board_name">NAME:<b><!###BOARD_NAME###!></b></span>
                <span class="board_date">DATE:<b><!###BOARD_DATE###!></b></span>
                <span class="board_id">ID:<b><!###BOARD_ID###!></b></span>
        </div>
        <div class="board_body"><!###BOARD_BODY###!></div>
